name: app
description: A new Flutter project.


version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.0
  flutter_profile_picture: ^2.0.0
  google_maps_flutter: ^2.4.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/